# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
sauvignon_blanc = Wine.create(varietal: "sauvignon blanc", category: "white")
chardonnay = Wine.create(varietal: "chardonnay", category: "white")
pinot_noir = Wine.create(varietal: "pinot noir", category: "red")
merlot = Wine.create(varietal: "merlot", category: "red")
zinfandel = Wine.create(varietal: "zinfandel", category: "red")
syrah = Wine.create(varietal: "syrah", category: "red")
cabernet_sauvignon= Wine.create(varietal: "cabernet sauvignon", category: "red")
malbec = Wine.create(varietal: "malbec", category:"red")
lambrusco = Wine.create(varietal: "lambrusco", category:"sparkling")


feta_cheese = Food.create(name: "feta cheese", category: "cheese")
goat_cheese = Food.create(name: "goat cheese", category: "cheese")
almond = Food.create(name: "almond", category: "nut")
chicken = Food.create(name: "chicken", category: "meat")
salmon = Food.create(name: "salmon", category: "fish")
tuna = Food.create(name: "tuna", category: "fish")
apple = Food.create(name: "apple", category: "fruit")
shrimp = Food.create(name: "shrimp", category: "fish")
crab = Food.create(name: "crab", category: "fish")
lobster = Food.create(name: "lobster", category: "fish")
steak = Food.create(name: "steak", category: "meat")
cured_meat = Food.create(name: "cured meat", category: "meat")
pork = Food.create(name: "pork", category: "meat")

Pairing.create(food: feta_cheese, wine: sauvignon_blanc)
Pairing.create(food: apple, wine: sauvignon_blanc)
Pairing.create(food: goat_cheese, wine: sauvignon_blanc)
Pairing.create(food: chicken, wine: sauvignon_blanc)
Pairing.create(food: pork, wine: sauvignon_blanc)
Pairing.create(food: shrimp, wine: sauvignon_blanc)
Pairing.create(food: crab, wine: sauvignon_blanc)
Pairing.create(food: lobster, wine: sauvignon_blanc)
Pairing.create(food: almond, wine: chardonnay)
Pairing.create(food: apple, wine: chardonnay)
Pairing.create(food: chicken, wine: chardonnay)
Pairing.create(food: pork, wine: chardonnay)
Pairing.create(food: shrimp, wine: chardonnay)
Pairing.create(food: crab, wine: chardonnay)
Pairing.create(food: lobster, wine: chardonnay)
Pairing.create(food: goat_cheese, wine: pinot_noir)
Pairing.create(food: salmon, wine: pinot_noir)
Pairing.create(food: tuna, wine: pinot_noir)
Pairing.create(food: chicken, wine: pinot_noir)
Pairing.create(food: tuna, wine: syrah)
Pairing.create(food: salmon, wine: syrah)
Pairing.create(food: cured_meat, wine: syrah)
Pairing.create(food: tuna, wine: merlot)
Pairing.create(food: steak, wine: merlot)
Pairing.create(food: tuna, wine: cabernet_sauvignon)
Pairing.create(food: steak, wine: cabernet_sauvignon)
